### ISSUE TITLE
cue is always preload audio

### ISSUE THREAD

**Issue by panshengjie** [audiotheme/cue#13]
cue is always preload audio(version 2.1.1), count 20%~25% of the audio
when I check into the code, in templates/playlist.php in 'audio' tag, it was marked as preload="none", however, doesn't work

I  insert audio in wordpress by default way (with [audio]), it works well 
but in your official website, cue player works well with no preload

that's weird

in addition, all of this are tested in chrome

**Comment by bradyvercher** [comment]
I've tested this in a couple of places and it appears to respect the preload setting. Do you have a link where I can view the behavior you're describing?

**Comment by panshengjie** [comment]
try this
http://pandaserver.jios.org:81/category/music/

**Comment by panshengjie** [comment]
I just find that preload works well with english songs, but fail to chinese songs

**Comment by bradyvercher** [comment]
I was seeing the same behavior and traced it down to our [jquery-cue](https://github.com/audiotheme/jquery-cue) library. It looks like the audio source is URI encoded, so [the comparison here fails](https://github.com/audiotheme/jquery-cue/blob/8e7430b5ec1de71bbe6c0097fcbf544ee3a08037/src/feature-playlist.js#L158), causing the track to be loaded. I'll try to get that fixed up and include it in the next release.

Thanks for the report!
