### ISSUE TITLE
How to enable auto play playlist in Cue?

### ISSUE THREAD

**Issue by vanloc0301** [audiotheme/cue#16]
I using Cue to create a playlist of the audio file. But when I open the page, it doesn’t have automatic play audio playlist. I must click button play to play audio. Have any function to do this? Thanks.

**Comment by bradyvercher** [comment]
Hi @vanloc0301, Cue doesn't include an autoplay feature. Mobile devices like iOS and Android, as well as Safari on desktop, have disabled autoplay completely. Aside from that, most users don't care for it, so it's not something that Cue supports.

**Comment by vanloc0301** [comment]
Hi @bradyvercher ,

Normally, the user doesn't need function auto-play.

In my case, I make a website audiobook, I upload my audio to archive.org. When the user login to my website to hear audio, the function autoplay is must have the function.

I saw on this webpage have this function: http://truyenaudiomoi.com/de-thi-dam-mau/

![capture](https://user-images.githubusercontent.com/4168981/36992510-bfd22f6a-20dd-11e8-8a5a-61db63a426bd.PNG)

I can't find the name of this plugin. Do you know it the plugin? I'm really grateful if you tell me the name of the plugin.

**Comment by bradyvercher** [comment]
That is an example of autoplay. If you open it in Safari or on an iOS or Android device, you'll notice that it doesn't automatically play.

From what I can tell, that looks like a custom player built into the theme and isn't a plugin that's available for usage elsewhere.
